// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'import-error-import-failed'
  | 'import-error-no-entries'
  | 'import-error-parse-failed'
  | 'import-progress-importing'
  | 'import-progress-matching'
  | 'import-progress-parsing'
  | 'import-summary-ambiguous'
  | 'import-summary-created'
  | 'import-summary-matched'
  | 'menuitem-smart-import'
  | 'pref-help'
  | 'pref-match-threshold'
  | 'pref-new-item-tag'
  | 'pref-tag-new-items'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
